sudo: false

language: node_js
node_js:
    - "6"
    - "8"
    - "10"
    - "node"

cache:
  directories:
    - node_modules

notifications:
  email:
    - ci@sailsjs.com

matrix:
  fast_finish: true

script: "grunt"

after_success: istanbul-coveralls
